script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",8,"p", 0.1)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",7,"p", 0.2)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",6,"p", 0.3)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",5,"p", 0.4)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",4,"p", 0.5)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",3,"p", 0.6)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",2,"p", 0.7)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("b",1,"p", 0.8)

script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",8,"p", -0.1)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",7,"p", -0.2)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",6,"p", -0.3)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",5,"p", -0.4)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",4,"p", -0.5)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",3,"p", -0.6)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",2,"p", -0.7)
script.Parent.Parent.Parent.Main.Events.MOVE:Fire("a",1,"p", -0.8)
